### ISSUE TITLE
Components from /line folder unusable due to TV.js vs Tv.js compilation error

### ISSUE THREAD

**Issue by katzelein** [meetup/swarm-ui#121]
When trying to compile swarm-icons, there's a casing mismatch between the compiled name of a file `Tv.js` and the way it is being used in `lib/components/line/index.js`-- `TV.js`. If I fix the casing in the compiled `index.js`, it becomes usable. It looks like there is both a `TV.js` and `Tv.js` file in the uncompiled source files, which is probably the source or a side-effect of the issue.

**Comment by mmcgahan** [comment]
thanks for flagging this - probably better to raise it in Slack in #ask-web-platform in the future because I don't think we have notifications set up for GH Issues in our repos, but it should all be sorted now. You might have to run `rm -rf packages/swarm-icons/lib && yarn build` from the root of the repo to get back in action for development, but `@meetup/swarm-icons` version `0.1.1` includes the fix

**Comment by katzelein** [comment]
That's what I did in the past and was told to submit an issue here instead. It might be helpful to fill out the READMEs a bit.
